version: "3.8"
services:
  db:
    image: postgres:12.3
    hostname: localhost
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-vol:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    networks:
      external-network:  # usuwamy internal-network, aby udostępnić usługę z sieci zewnętrznej
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: food-watcher-app
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RELOAD=True
      - PORT=80
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    links:
      - "db:postgres"
    command: [ "python3", "-m", "src.api" ]
    volumes:
      - ./src:/app/src
    networks:
      external-network:  # usuwamy internal-network, aby udostępnić usługę z sieci zewnętrznej

networks:
  external-network:
    driver: bridge  # ustawiamy driver na bridge, aby usługa była dostępna z sieci zewnętrznej

volumes:
  postgres-vol: